api:
  path: "/api/v1"


spring:
  datasource:
    hikari:
      username: maple
      password: passw0rd
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true


